url: help.hanaro.agency
title: 하나로비서 도움말
description: 하나로비서의 고객을 위한 도움말 페이지입니다.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

collections:
  helps:
    output: true

defaults:
  - scope:
      path: ""
      type: "helps"
    values:
      layout: "help"